apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-web
  labels:
    app: comment-web
spec:
  replicas: 2
  selector:
    matchLabels:
      service: comments
      tier: web
  template:
    metadata:
      labels:
        service: comments
        tier: web
    spec:
      containers:
        - name: webserver
          image: busybox:1.36
          args:
            - /bin/sh
            - -c
            - >
              i=0;
              while true;
              do
                echo "OUT $(hostname) $(date)" >> /var/log/stdout.log;
                echo "ERROR $(hostname) $(date)" >> /var/log/stderr.log;
                sleep 5;
              done
          volumeMounts:
            - name: log
              mountPath: /var/log
        - name: stdout-sidecar
          image: busybox:1.36
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/stdout.log']
          volumeMounts:
            - name: log
              mountPath: /var/log
        - name: stderr-sidecar
          image: busybox:1.36
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/stderr.log']
          volumeMounts:
            - name: log
              mountPath: /var/log
      volumes:
        - name: log
          emptyDir: {}
